// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// API para acessar o firebase android
  static const apikeyandroid = String.fromEnvironment('APIKEYANDROID');

  /// API para acessar o firebase ios
  static const apikeyios = String.fromEnvironment('APIKEYIOS');
}

    