
name: Flutter CI/CD

on:
  push:
      branches:
            - ci/buildpipeline
jobs: #build do ios e android
 build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Verify Flutter Installation
        run: flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Install System Dependencies
        run: 
         sudo apt-get update
         sudo apt-get install -y curl git unzip xz-utils libglu1-mesa
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
                path: ~/.pub-cache
                key: ${{ runner.os }}-pub-${{ hashFiles('\*\*/pubspec.yaml') }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
                flutter-version: "3.13.3"
      - name: Install CocoaPods
        run: pod install --project-directory=ios
      - name: Build APK
        run: flutter build apk --release
      - name: Build iOS
        run: flutter build ios --release
      - name: Run Tests
        run: flutter test

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
                name: app-release.apk #a ser modificado
                path: build/app/outputs/flutter-apk/app-release.apk
        
