name: Flutter Build Pipeline

on:
  workflow_run:
    workflows: ["Flutter Test Pipeline"]
    types:
      - completed

jobs:
  build-app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Clonar repositório
      - name: Clone repository
        uses: actions/checkout@v4

      # Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Configurar Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Instalar dependências do sistema
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      # Verificar instalação do Flutter
      - name: Verify Flutter Installation
        run: flutter --version

      # Limpar build anterior
      - name: Clean Flutter Build
        run: flutter clean

      # Instalar dependências do projeto
      - name: Install Dependencies
        run: flutter pub get

      # Cache de dependências
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Build APK para release
      - name: Build APK (Release)
        run: flutter build apk --release --dart-define=apiKeyAndroid=${{ secrets.APIKEYANDROID }} --dart-define=apiKeyIos=${{ secrets.APIKEYIOS }}

      # Upload do APK gerado
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Notificação de sucesso do build
      - name: Notify Build Success
        run: echo "Build completed successfully. APK is ready."
